version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: wazimap-sifar
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    expose:
      - "8000"
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/sifar
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: wazimap-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data:
