# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-26 13:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('settlement', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('facility_code', models.CharField(max_length=20, unique=True)),
                ('geo_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('dataset', models.CharField(max_length=50)),
                ('service', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'health_facilities',
            },
        ),
        migrations.AlterUniqueTogether(
            name='healthfacilities',
            unique_together=set([('name', 'latitude', 'longitude', 'facility_code')]),
        ),
    ]
