# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-26 14:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0002_auto_20181126_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('details', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'professional_service',
            },
        ),
    ]
