# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-26 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0003_professionalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservice',
            name='service_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
