# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0004_professionalservice_service_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservice',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
