# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-27 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0006_professionalservice_geo_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('library_type', models.CharField(blank=True, max_length=100)),
                ('members', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'library',
            },
        ),
        migrations.AlterUniqueTogether(
            name='library',
            unique_together=set([('name', 'latitude', 'longitude', 'library_type')]),
        ),
    ]
