# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-29 10:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0008_library_geo_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geo_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'community_parks',
            },
        ),
        migrations.CreateModel(
            name='DistrictPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geo_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'distirct_parks',
            },
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'libraries'},
        ),
        migrations.AlterUniqueTogether(
            name='districtpark',
            unique_together=set([('name', 'suburb')]),
        ),
        migrations.AlterUniqueTogether(
            name='communitypark',
            unique_together=set([('name', 'suburb')]),
        ),
    ]
