# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-29 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0009_auto_20181129_1206'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='districtpark',
            table='district_parks',
        ),
    ]
