# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0010_auto_20181129_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatepharmacy',
            old_name='facility',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='privatepharmacy',
            unique_together=set([('name', 'latitude', 'longitude', 'organization_unit_type')]),
        ),
    ]
