# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0011_auto_20190313_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('subcategory', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sifar_datasets',
                'verbose_name': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='DatasetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sifar_dataset_category',
                'verbose_name': 'Dataset Category',
            },
        ),
        migrations.DeleteModel(
            name='CommunityPark',
        ),
        migrations.DeleteModel(
            name='DistrictPark',
        ),
        migrations.DeleteModel(
            name='HealthFacilities',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='PrivatePharmacy',
        ),
        migrations.DeleteModel(
            name='ProfessionalService',
        ),
        migrations.AddField(
            model_name='dataset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap_sifar.DatasetCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('category', 'subcategory')]),
        ),
    ]
