# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0012_auto_20190513_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
