# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0015_dataset_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('category', 'subcategory', 'address', 'name')]),
        ),
    ]
