# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0018_contributer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributer',
            old_name='dataset',
            new_name='subcategory',
        ),
        migrations.AddField(
            model_name='dataset',
            name='contributer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wazimap_sifar.Contributer'),
        ),
    ]
