# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0020_auto_20190513_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={},
        ),
        migrations.AddField(
            model_name='contributer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wazimap_sifar.DatasetCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('address', 'name', 'latitude', 'longitude')]),
        ),
        migrations.AlterModelTable(
            name='dataset',
            table='sifar_dataset',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='subcategory',
        ),
    ]
