# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0021_auto_20190529_2013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('address', 'name', 'latitude', 'longitude', 'contributer')]),
        ),
    ]
