# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-16 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0022_auto_20190529_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetcategory',
            options={'verbose_name_plural': 'Dataset Categories'},
        ),
    ]
