# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0023_auto_20190816_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='contributer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wazimap_sifar.Contributer', verbose_name='Source'),
        ),
    ]
