# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-30 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0024_auto_20190902_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributer',
            new_name='Contributor',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
