# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-31 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0025_auto_20200330_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
