# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-31 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0026_auto_20200331_1207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set([('category', 'subcategory')]),
        ),
    ]
