# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-01 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0027_auto_20200331_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='contributer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wazimap_sifar.Contributor', verbose_name='Contributor'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
