# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_sifar', '0028_auto_20200401_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
